apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-service
  namespace: frontend-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-service
  template:
    metadata:
      labels:
        app: image-service
    spec:
      containers:
      - name: image-service
        image: karar99/image-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
        env:
        - name: DATABASE_URL
          value: jdbc:postgresql://postgres-service:5432/userdb
        - name: DATABASE_USERNAME
          value: postgres
        - name: DATABASE_PASSWORD
          value: postgres123
        - name: MINIO_ENDPOINT
          value: http://minio:9000
        - name: MINIO_ACCESS_KEY
          value: minioadmin
        - name: MINIO_SECRET_KEY
          value: minioadmin123
        - name: MINIO_BUCKET
          value: profile-pictures
---
apiVersion: v1
kind: Service
metadata:
  name: image-service
  namespace: frontend-backend
spec:
  selector:
    app: image-service
  ports:
  - port: 8081
    targetPort: 8081
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: image-service-ingress
  namespace: frontend-backend
spec:
  ingressClassName: nginx
  rules:
  - host: images.k8s.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: image-service
            port:
              number: 8081
