spring:
  application:
    name: image-service
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://postgres-service:5432/userdb}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres123}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8081
logging:
  level:
    root: INFO
    com.playground.imageservice: DEBUG
